[theme]
base = "light"
primaryColor = "#0F172A"
backgroundColor = "#FAFAFA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0F172A"
font = "sans serif"

[server]
runOnSave = true
headless = true

[browser]
gatherUsageStats = false
